### ISSUE TITLE
Does Teo support SSR for Astro or Vue, particularly in Rust and Python?

### ISSUE THREAD

**Issue by jeromeleong** [teodevgroup/teo#64]
I'm exploring the use of Teo for server-side rendering (SSR), and I'm curious to know if it supports SSR for frameworks like Astro or Vue. Specifically, I'm interested in implementing this functionality in Rust and Python. Has anyone already implemented SSR for these frameworks within Teo, or are there any related documentation or tutorials available for reference?

**Comment by victorteokw** [comment]
Hi @jeromeleong, Teo will not directly support frontend techs even SSR. But you can integrate by yourself.
