### ISSUE TITLE
Error generate admin

### ISSUE THREAD

**Issue by linpete-proto** [teodevgroup/teo#65]
First - thx for this great project - i like it very much!

By trying Generate admin dashboard from the tutorial i get an error at 

cargo teo generate admin
Error: Error { code: 500, message: "error decoding response body", errors: None, platform_native_object: None }

Backend ist up and running

cargo teo serve
[2024-06-12 08:18:41] sqlite connector connected for `main` at "sqlite:./database.sqlite"
[2024-06-12 08:18:41] Teo 0.2.35 (Rust 1.78.0, CLI)
[2024-06-12 08:18:41] listening on port 5054

This seems due to some kind of misffits in the serde json deserialization of the repsonse body?

**Comment by victorteokw** [comment]
Hi @linpete-proto, I forgot to update the admin template to the latest version.

**Comment by victorteokw** [comment]
This is fixed.

**Comment by Howe829** [comment]
<img width="1459" alt="image" src="https://github.com/teodevgroup/teo/assets/28386363/d988bd8b-824d-4d2c-af5c-798170d45bff">
how about python version? @victorteokw

**Comment by Howe829** [comment]
> <img alt="image" width="1459" src="https://private-user-images.githubusercontent.com/28386363/343657592-d988bd8b-824d-4d2c-af5c-798170d45bff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzEwNTQsIm5iZiI6MTcxOTQ3MDc1NCwicGF0aCI6Ii8yODM4NjM2My8zNDM2NTc1OTItZDk4OGJkOGItODI0ZC00ZDJjLWFmNWMtNzk4MTcwZDQ1YmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA2NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2ZlY2FiNjk3MjcwZWQ1MDhhOTU3Yjc2ZDA2MTI3ZGUzOTRlMDM1Nzk2YTkxZTA1OTcyN2VlYWRmOWU2ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.56bC2cf3Eg-SF6FDJRfRw7M7s_--keZ_xR9dxsuovO8"> Hi @victorteokw how about python version?

Ok, I think it was something wrong with my network.

**Comment by victorteokw** [comment]
Hi @linpete-proto, yup, we need to fetch GitHub for the admin template.
