### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by akelyasir** [teodevgroup/teo#72]
Hi,

I downloaded all the files with teo-development-setup. It gave an error while trying to build Teo. 

`error: failed to select a version for the requirement `teo-generator = "^0.3.0-alpha.0"``

Then I changed the 0.3.0-alpha-dev branch for all packages. This time I got a different error.

`error: could not compile `quaint-forked` (lib) due to 1 previous error`

```
error[E0283]: type annotations needed
   --> /home/yasirakel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/quaint-forked-0.1.3-alpha.6/src/connector/postgres.rs:468:37
    |
468 |         config.user(self.username().borrow());
    |                                     ^^^^^^
    |
    = note: multiple `impl`s satisfying `Cow<'_, str>: Borrow<_>` found in the following crates: `alloc`, `core`:
            - impl<'a, B> Borrow<B> for Cow<'a, B>
              where B: ToOwned, B: ?Sized;
            - impl<T> Borrow<T> for T
              where T: ?Sized;
help: try using a fully qualified path to specify the expected types
    |
468 |         config.user(<Cow<'_, str> as Borrow<Borrowed>>::borrow(&self.username()));
    |                     ++++++++++++++++++++++++++++++++++++++++++++  
```

When exactly can I start using Teo?

Thanks

**Comment by victorteokw** [comment]
Hi @akelyasir, 0.3.0-alpha.1 is going to be released soon. I will dig into this.

**Comment by eswr** [comment]
I am able to install teo using cargo
1. clone the repo
        https://github.com/teodevgroup/teo/blob/main/CONTRIBUTING.md#github-source
2. clone quaint 
        https://github.com/victorteokw/quaint
3. make this change and build
        // config.user(self.username().borrow());
        config.user(<std::borrow::Cow<'_, str> as std::borrow::Borrow<str>>::borrow(&self.username()));
4. Update the teo-sql-connector and build
        quaint-forked = { version = "0.1.3-alpha.6", features = [ "postgresql" ], path = "../quaint-forked" }
5. open teo and the local version
        cargo install --path .

**Comment by akelyasir** [comment]
Hi @victorteokw

It's been a long time since I didn't get an update. Is there a specific time for the update.

**Comment by victorteokw** [comment]
This is fixed in newest quaint forked
